insert into MVW_MANNSCHAFT (name, typ, gewonnene_spiele, gesamte_spiele) values ('1. FC Köln', 'FUSSBALL', 1, 2);
insert into MVW_MANNSCHAFT (name, typ, gewonnene_spiele, gesamte_spiele) values ('2. FC Köln', 'FUSSBALL', 0, 0);
insert into MVW_MANNSCHAFT (name, typ, gewonnene_spiele, gesamte_spiele) values ('FC Bayern München', 'FUSSBALL', 0, 2);
insert into MVW_MANNSCHAFT (name, typ, gewonnene_spiele, gesamte_spiele) values ('Leverkusen', 'FUSSBALL', 0, 1);
insert into MVW_MANNSCHAFT (name, typ, gewonnene_spiele, gesamte_spiele) values ('THW Kiel', 'HANDBALL', 1, 1);
insert into MVW_MANNSCHAFT (name, typ, gewonnene_spiele, gesamte_spiele) values ('Füchse', 'HANDBALL', 0, 1);
insert into MVW_MANNSCHAFT (name, typ, gewonnene_spiele, gesamte_spiele) values ('Friesdorf', 'HANDBALL', 0, 1);
insert into MVW_MANNSCHAFT (name, typ, gewonnene_spiele, gesamte_spiele) values ('TV Blau-Weiß Eitorf', 'TENNIS', 1, 2);
insert into MVW_MANNSCHAFT (name, typ, gewonnene_spiele, gesamte_spiele) values ('TV Grün-Gelb Dottendorf', 'TENNIS', 0, 2);
insert into MVW_MANNSCHAFT (name, typ, gewonnene_spiele, gesamte_spiele) values ('Funkensterne', 'TENNIS', 2, 2);

insert into MVW_SPIEL (TITEL, MANNSCHAFT_A_FK, MANNSCHAFT_B_FK, RESULT_A, RESULT_B) values ('1. Bundesliga, 6 T', 1, 3, 2, 0);
insert into MVW_SPIEL (TITEL, MANNSCHAFT_A_FK, MANNSCHAFT_B_FK, RESULT_A, RESULT_B) values ('1. Bundesliga, 7 T', 4, 1, 0, 0);
insert into MVW_SPIEL (TITEL, MANNSCHAFT_A_FK, MANNSCHAFT_B_FK, RESULT_A, RESULT_B) values ('Kreisligamatch #441', 5, 6, 13, 12);
insert into MVW_SPIEL (TITEL, MANNSCHAFT_A_FK, MANNSCHAFT_B_FK, RESULT_A, RESULT_B) values ('Erste Bundesliga', 3, 4, 4, 4);
insert into MVW_SPIEL (TITEL, MANNSCHAFT_A_FK, MANNSCHAFT_B_FK, RESULT_A, RESULT_B) values ('Freundschaftsspiel', 6, 7, 5, 4);
insert into MVW_SPIEL (TITEL, MANNSCHAFT_A_FK, MANNSCHAFT_B_FK, RESULT_A, RESULT_B) values ('Testspiel', 2, 4, 0, 0);
insert into MVW_SPIEL (TITEL, MANNSCHAFT_A_FK, MANNSCHAFT_B_FK, RESULT_A, RESULT_B) values ('Einzel', 8, 9, 3, 2);
insert into MVW_SPIEL (TITEL, MANNSCHAFT_A_FK, MANNSCHAFT_B_FK, RESULT_A, RESULT_B) values ('Doppel', 9, 10, 1, 3);
insert into MVW_SPIEL (TITEL, MANNSCHAFT_A_FK, MANNSCHAFT_B_FK, RESULT_A, RESULT_B) values ('Turnier', 10, 8, 3, 2);

insert into MVW_PERSON (VORNAME, NACHNAME, GEBURTSDATUM) values ('Marvin', 'Zichner', STR_TO_DATE('09.08.1999', '%d.%m.%Y'));
insert into MVW_PERSON (VORNAME, NACHNAME, GEBURTSDATUM) values ('Yannick', 'Zichner', STR_TO_DATE('08.08.2004', '%d.%m.%Y'));
insert into MVW_PERSON (VORNAME, NACHNAME, GEBURTSDATUM) values ('John', 'Wayne', STR_TO_DATE('07.03.2003', '%d.%m.%Y'));
insert into MVW_PERSON (VORNAME, NACHNAME, GEBURTSDATUM) values ('Peter', 'Lustig-Bongartz', STR_TO_DATE('12.07.1989', '%d.%m.%Y'));
insert into MVW_PERSON (VORNAME, NACHNAME, GEBURTSDATUM) values ('Otto', 'Fröhlich', STR_TO_DATE('20.01.2001', '%d.%m.%Y'));
insert into MVW_PERSON (VORNAME, NACHNAME, GEBURTSDATUM) values ('Hans', 'Schmitz', STR_TO_DATE('04.07.1999', '%d.%m.%Y'));
insert into MVW_PERSON (VORNAME, NACHNAME, GEBURTSDATUM) values ('Waldemar', 'Kopernikus', STR_TO_DATE('15.09.1971', '%d.%m.%Y'));
insert into MVW_PERSON (VORNAME, NACHNAME, GEBURTSDATUM) values ('Spiggi', 'Johnson', STR_TO_DATE('09.08.1985', '%d.%m.%Y'));
insert into MVW_PERSON (VORNAME, NACHNAME, GEBURTSDATUM) values ('Hubert-Günther', 'Hufnagel', STR_TO_DATE('30.04.1950', '%d.%m.%Y'));
insert into MVW_PERSON (VORNAME, NACHNAME, GEBURTSDATUM) values ('Dorothee', 'Michael', STR_TO_DATE('24.12.1998', '%d.%m.%Y'));
insert into MVW_PERSON (VORNAME, NACHNAME, GEBURTSDATUM) values ('Angelika', 'Abt-Schmitz', STR_TO_DATE('23.02.1991', '%d.%m.%Y'));

insert into MVW_FUSSBALLSPIELER (PERSON_FK, SPIELERROLLE_FK, GEWONNENE_SPIELE, LEFT_FOOT) values (1, 1, 0, 0);
insert into MVW_FUSSBALLSPIELER (PERSON_FK, SPIELERROLLE_FK, GEWONNENE_SPIELE, LEFT_FOOT) values (2, 1, 1, 1);
insert into MVW_TRAINER (PERSON_FK, SPIELERROLLE_FK, GEWONNENE_SPIELE, HAS_LICENSE) values (3, 4, 1, 1);
insert into MVW_HANDBALLSPIELER (PERSON_FK, SPIELERROLLE_FK, GEWONNENE_SPIELE, LEFT_HAND) values (4, 3, 5, 0);
insert into MVW_HANDBALLSPIELER (PERSON_FK, SPIELERROLLE_FK, GEWONNENE_SPIELE, LEFT_HAND) values (5, 3, 5, 0);
insert into MVW_PHYSIOTHERAPEUT (PERSON_FK, SPIELERROLLE_FK, HAS_LICENSE) values (6, 3, 1);
insert into MVW_PHYSIOTHERAPEUT (PERSON_FK, SPIELERROLLE_FK, HAS_LICENSE) values (7, 3, 1);
insert into MVW_TENNISSPIELER (PERSON_FK, SPIELERROLLE_FK, GEWONNENE_SPIELE, LEFT_ARM) values (11, 2, 1, 1);
insert into MVW_TENNISSPIELER (PERSON_FK, SPIELERROLLE_FK, GEWONNENE_SPIELE, LEFT_ARM) values (8, 2, 1, 0);
insert into MVW_TENNISSPIELER (PERSON_FK, SPIELERROLLE_FK, GEWONNENE_SPIELE, LEFT_ARM) values (9, 2, 1, 1);
insert into MVW_PHYSIOTHERAPEUT (PERSON_FK, SPIELERROLLE_FK, HAS_LICENSE) values (10, 3, 1);
